#!/bin/bash
#PBS -N PARCO_SpMV
#PBS -o ./PARCO_SpMV_Serial.o
#PBS -e ./PARCO_SpMV_Serial.e
#PBS -q short_cpuQ
#PBS -l walltime=0:40:00
#PBS -l select=1:ncpus=1:mem=1mb

# Modules for C
module load gcc91
gcc() {
    gcc-9.1.0 "$@"
}
gcc --version
# Select the working directory
cd "$PBS_O_WORKDIR"   # go to the directory where qsub was run

echo "Running in: $(pwd)"

# The code should be compiled before submitting the job
make run
