#!/bin/bash
#PBS -N PARCO_SpMV
#PBS -o ./PARCO_SpMV_Serial.o
#PBS -e ./PARCO_SpMV_Serial.e
#PBS -q short_cpuQ
#PBS -l walltime=06:00:00
#PBS -l select=1:ncpus=96:mem=50gb

# Modules for C
module load gcc91
module load python-3.10.14

export OMP_PROC_BIND=close
export OMP_PLACES=cores
export OMP_DYNAMIC=false
export OMP_WAIT_POLICY=active

gcc() {
    gcc-9.1.0 "$@"
}
gcc --version
cd "$PBS_O_WORKDIR"

echo "Running in: $(pwd)"

./Run.sh "$MATRIX" "$OUTPUT_DIR" "$GRAPH_DIR"
