#include "DataFactory.h"

#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <stdlib.h>

int writeCOOAsMatrixMarket(const char *filename, const COOMatrix *m) {
    FILE *f = fopen(filename, "w");
    if (!f) {
        fprintf(stderr, "Cannot open file %s: %s\n", filename, strerror(errno));
        return -1;
    }

    if (fprintf(f, "%%MatrixMarket matrix coordinate real general\n") < 0) { fclose(f); return -1; }
    if (fprintf(f, "%% Generated by data_factory\n") < 0) { fclose(f); return -1; }

    if (fprintf(f, "%d %d %d\n", m->rows, m->cols, m->nnz) < 0) { fclose(f); return -1; }

    for (int k = 0; k < m->nnz; ++k) {
        int r = m->row[k] + 1;
        int c = m->col[k] + 1;
        double v = m->val[k];
        if (fprintf(f, "%d %d %.17g\n", r, c, v) < 0) {
            fprintf(stderr, "Error while wrting file %s\n", filename);
            fclose(f);
            return -1;
        }
    }

    if (fclose(f) != 0) {
        fprintf(stderr, "Error while closing file %s\n", filename);
        return -1;
    }
    return 0;
}

void createWeakScalingDataset(const int rows, const int cols, const int nnz) {
    COOMatrix m;
    randomInitCOO(&m, rows, cols, 4, nnz);

    char filename[256];
    if (snprintf(filename, sizeof(filename), "matrix_weak_scaling_%d_%d_%d.mtx", rows, cols, nnz) >= (int)sizeof(filename)) {
        fprintf(stderr, "Name is too long\n");
        return;
    }

    if (writeCOOAsMatrixMarket(filename, &m) != 0) {
        fprintf(stderr, "Could not export matrix to file\n");
    }
    free(m.row);
    free(m.col);
    free(m.val);

}
